#!/bin/bash

echo "=== 主题管理系统编译指南 ==="
echo ""
echo "步骤 1: 打开项目"
echo "打开 .xcworkspace 文件"
echo "路径: tarot_cards.xcworkspace"
echo ""
echo "步骤 2: 编译项目"
echo "在 Xcode 中按 Cmd+B (Build)"
echo ""
echo "步骤 3: 运行应用"
echo "在 Xcode 中按 Cmd+R (Run)"
echo ""
echo "步骤 4: 测试主题切换"
echo "1. 进入「占卜师」页面"
echo "2. 选择不同的占卜师"
echo "3. 验证主题颜色变化"
echo ""
echo "步骤 5: 测试持久化"
echo "1. 选择一个占卜师"
echo "2. 完全关闭应用"
echo "3. 重新打开应用"
echo "4. 验证是否记住之前的选择"
echo ""
echo "=== 完成 ==="
